typography_spectrum: 0.4202851091977209
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7408501417376101
  lightness: 0.5728659422602504
  saturation: 0.090455457335338
  rhythmicContrast: 0.027541505405679345
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3424485959112644
analytics:
  google: null
  facebook: null
  twitter: null
name: Frank Fredericks
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Frank Fredericks
description: Entrepreneur | Interfaith Activist | Communicator
purpose: []
